services:
  db:
    build: .
    container_name: omnipath_postgres_container
    restart: always  # Restart the database if it crashes
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: omnipath_admin_123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  # Map PostgreSQL port to the host
    volumes:
      - pg_data:/var/lib/postgresql/data  # Persist database data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Run initial SQL script

volumes:
  pg_data:  # Named volume for database persistence