# Generated by Django 5.1.6 on 2025-03-10 01:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionsOmnipath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, null=True)),
                ('target', models.CharField(blank=True, null=True)),
                ('source_genesymbol', models.CharField(blank=True)),
                ('target_genesymbol', models.CharField(blank=True)),
                ('is_directed', models.BooleanField()),
                ('is_stimulation', models.BooleanField()),
                ('is_inhibition', models.BooleanField()),
                ('consensus_direction', models.BooleanField()),
                ('consensus_stimulation', models.BooleanField()),
                ('consensus_inhibition', models.BooleanField()),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('references', models.CharField(blank=True)),
                ('omnipath', models.BooleanField()),
                ('kinaseextra', models.BooleanField()),
                ('ligrecextra', models.BooleanField()),
                ('pathwayextra', models.BooleanField()),
                ('mirnatarget', models.BooleanField()),
                ('dorothea', models.BooleanField()),
                ('collectri', models.BooleanField()),
                ('tf_target', models.BooleanField()),
                ('lncrna_mrna', models.BooleanField()),
                ('tf_mirna', models.BooleanField()),
                ('small_molecule', models.BooleanField()),
                ('dorothea_curated', models.BooleanField()),
                ('dorothea_chipseq', models.BooleanField()),
                ('dorothea_tfbs', models.BooleanField()),
                ('dorothea_coexp', models.BooleanField()),
                ('dorothea_level', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('type', models.CharField(blank=True)),
                ('curation_effort', models.IntegerField()),
                ('extra_attrs', models.JSONField(blank=True, null=True)),
                ('evidences', models.JSONField(blank=True, null=True)),
                ('ncbi_tax_id_source', models.IntegerField()),
                ('entity_type_source', models.CharField(blank=True)),
                ('ncbi_tax_id_target', models.IntegerField()),
                ('entity_type_target', models.CharField(blank=True)),
            ],
            options={
                'verbose_name': 'Interactions Omnipath',
                'db_table': 'interactions_omnipath',
                'ordering': ('id',),
            },
        ),
    ]
